import fs from "fs";
import path from "path";

const ROOT = path.join(__dirname, "..", "..");

test("synced Henry working files are present (sync:henry ran)", () => {
  const vendor = path.join(ROOT, "src", "vendor", "henry");
  expect(fs.existsSync(path.join(vendor, "henry-animated.css"))).toBe(true);
  expect(fs.existsSync(path.join(vendor, "henry-illustration-glitched.svg"))).toBe(true);
  expect(fs.existsSync(path.join(ROOT, "public", "favicon.ico"))).toBe(true);
});

test("synced targets are gitignored (no committed duplicates)", () => {
  const gi = fs.readFileSync(path.join(ROOT, ".gitignore"), "utf8");
  expect(gi).toMatch(/\/src\/vendor\/henry\//);
  expect(gi).toMatch(/\/public\/favicon\.ico/);
});

// The fallback public/404.html is generated by sync-henry.js from
// scripts/404.template.html with the vendored henry-animated.css inlined, so
// the page stays self-contained without re-authoring Henry by hand.
const readPage = () => fs.readFileSync(path.join(ROOT, "public", "404.html"), "utf8");
const readTemplate = () =>
  fs.readFileSync(path.join(ROOT, "scripts", "404.template.html"), "utf8");

test("fallback 404 page inlines the vendored henry-animated.css verbatim", () => {
  const vendored = fs.readFileSync(
    path.join(ROOT, "src", "vendor", "henry", "henry-animated.css"),
    "utf8"
  );
  expect(readPage()).toContain(vendored.trim());
});

test("fallback 404 page renders the cute-robot- markup contract (confused pose)", () => {
  const page = readPage();
  expect(page).toContain("cute-robot-container cute-robot-has-question");
  expect(page).toContain("class=\"cute-robot-q cute-robot-q-main\"");
  expect(page).toContain("class=\"cute-robot-head\"");
});

test("fallback 404 page carries no hand-authored Henry geometry", () => {
  const page = readPage();
  expect(page).not.toMatch(/\n\s*\.head\s*\{/);
  expect(page).not.toMatch(/\n\s*\.antenna\s*\{/);
  expect(page).not.toMatch(/@keyframes blink\b/);
});

test("404 template carries the placeholder, not Henry", () => {
  const tpl = readTemplate();
  expect(tpl).toContain("/* @henry-animated-css */");
  expect(tpl).not.toMatch(/\.cute-robot-head\s*\{/);
  expect(tpl).not.toMatch(/\n\s*\.head\s*\{/);
});

test("generated 404 page is gitignored", () => {
  const gi = fs.readFileSync(path.join(ROOT, ".gitignore"), "utf8");
  expect(gi).toMatch(/^\/public\/404\.html$/m);
});
